target 'tools' do
    pod 'SocketRocket'
    pod 'ReactiveObjC'
    pod 'SDWebImage'
    pod 'YYKit'
    pod 'YTKNetwork'
    pod 'pop'
    pod 'FMDB'
    pod 'Shimmer'
    pod 'QMUIKit'
    pod 'Masonry'
    pod 'MQTTClient'
    pod 'CocoaAsyncSocket'
    pod 'PNChart'
    pod 'GPUImage'
    pod 'KVOController'
end
